version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: strudelshop_mssql
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  webapi:
    build: 
      context: .
      dockerfile: src/WebAPI/Dockerfile
    container_name: strudelshop_webapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: ${CONNECTION_STRING}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      JWT_KEY: ${JWT_KEY}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWT_TOKEN_EXPIRY_MINUTES: ${JWT_TOKEN_EXPIRY_MINUTES}
    ports:
      - "8080:8080"
    depends_on:
      - mssql
    env_file:
      - .env   

volumes:
  mssql_data:
