CREATE TABLE Product
(
	ProductId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(100) NOT NULL,
	Description NVARCHAR(255) NOT NULL,
	Price DECIMAL(10,2) NOT NULL,
	ImageURL NVARCHAR(255) NOT NULL
)
